= Billing and Invoice example with variables rates

== How to run these examples

[source,bash]
.Get link:https://github.com/tackler-ng/tackler[tackler]:
----
cargo install --locked tackler
----

[source,bash]
.Get example journal:
----
git clone https://github.com/tackler-ng/tm-rates-journal journal
----

After that you can run following examples on 
Linux/MacOS assuming that you have GNU date installed.

See link:https://tackler.fi/docs/tackler/latest/[Tackler Documentation] for detailed 
information and additional link:https://tackler.fi/docs/tackler/latest/examples/[Examples].

Tackler source code is located at 
link:https://github.com/tackler-ng/tackler[tackler-ng/tackler] on GitHub.

== Client status (saldos) 

[source,bash]
.Client saldos (time and material) for Jan
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --api-filter-def $(sh bin/filters/time.sh 2025-01-01 2025-02-01) \
   --reports balance \
   --accounts 'Client:.*:.*' \
   --invert
----

[source,bash]
.Client saldos (in Euros) for Jan
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --api-filter-def $(sh bin/filters/time.sh 2025-01-01 2025-02-01) \
   --accounts 'Client:.*:.*' \
   --price.lookup-type txn-time \
   --reports balance \
   --invert
----


== Billing statements

=== Invoices for Acme, Jan 2025

[source,bash]
.Billing summary of Jan 2025 for Acme (T&M)
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --api-filter-def $(sh bin/filters/billing.sh Acme 2025-01-01 2025-02-01) \
   --accounts 'Billing:Acme:.*' \
   --reports balance
----

[source,bash]
.Billing summary of Jan 2025 for Acme (Euros)
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --api-filter-def $(sh bin/filters/billing.sh Acme 2025-01-01 2025-02-01) \
   --accounts 'Billing:Acme:.*' \
   --price.lookup-type txn-time \
   --reports balance
----

[source,bash]
.Billing txn of Jan 2025 for Acme
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --api-filter-def $(sh bin/filters/billing.sh Acme 2025-01-01 2025-02-01) \
   --accounts 'Billing:Acme:.*' \
   --price.lookup-type txn-time \
   --exports equity \
   --invert \
   --output.dir tmp \
   --output.prefix 2025-02-02-acme
----

[source,bash]
.Invoice details of Jan 2025 for Acme
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --api-filter-def $(sh bin/filters/billing.sh Acme 2025-01-01 2025-02-01) \
   --accounts 'Billing:Acme:.*' \
   --price.lookup-type txn-time \
   --reports register
----

=== Invoices for Initech, Jan 2025

[source,bash]
.Billing summary of Jan 2025 for Initech (T&M)
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --api-filter-def $(sh bin/filters/billing.sh Initech 2025-01-01 2025-02-01) \
   --accounts 'Billing:Initech:.*' \
   --reports balance
----

[source,bash]
.Billing summary of Jan 2025 for Initech (Euros)
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --api-filter-def $(sh bin/filters/billing.sh Initech 2025-01-01 2025-02-01) \
   --accounts 'Billing:Initech:.*' \
   --price.lookup-type txn-time \
   --reports balance
----

[source,bash]
.Billing txn of Jan 2025 for Initech
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --api-filter-def $(sh bin/filters/billing.sh Initech 2025-01-01 2025-02-01) \
   --accounts 'Billing:Initech:.*' \
   --price.lookup-type txn-time \
   --exports equity \
   --invert \
   --output.dir tmp \
   --output.prefix 2025-02-04-initech
----

[source,bash]
.Invoice details of Jan 2025 for Initech
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --api-filter-def $(sh bin/filters/billing.sh Initech 2025-01-01 2025-02-01) \
   --accounts 'Billing:Initech:.*' \
   --price.lookup-type txn-time \
   --reports register
----


== Payments


[source,bash]
.Payments as 2025-02-04 (none has paid)
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --input.git.ref 2025-02-04 \
   --accounts 'Invoices:.*' 'Payments:.*' \
   --reports balance
----

[source,bash]
.Payments as 2025-02-06 (Initech paid)
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --input.git.ref 2025-02-06 \
   --accounts 'Invoices:.*' 'Payments:.*' \
   --reports balance
----

[source,bash]
.Payments as 2025-02-08 (Acme paid)
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --input.git.ref 2025-02-08 \
   --accounts 'Invoices:.*' 'Payments:.*' \
   --reports balance
----

[source,bash]
.Register of invoices and payments
----
tackler \
   --config journal/conf/tackler.toml \
   --input.storage git \
   --accounts 'Invoices:.*' 'Payments:.*' \
   --reports register
----

